import "../styles/Legalstyle.css";

/**
 * Generated by Claude Code
 *
 * @returns {JSX.Element}
 * @constructor
 */
export const Legal = () => {
    const currentYear = new Date().getFullYear();

    return (
        <div className="legal-page">
            <header className="legal-header">
                <a href="/" className="legal-logo">Notes-AI</a>
                <nav className="legal-nav">
                    <a href="#about">About</a>
                    <a href="#privacy">Privacy</a>
                    <a href="#terms">Terms</a>
                    <a href="#contact">Contact</a>
                </nav>
            </header>

            <div className="legal-hero">
                <div className="legal-hero-inner">
                    <span className="legal-eyebrow">Legal &amp; Company Information</span>
                    <h1>Notes-AI</h1>
                    <p className="legal-tagline">
                        AI-powered note-taking and study guide generation for students and lifelong learners.
                    </p>
                </div>
            </div>

            <main className="legal-main">

                {/* ── ABOUT ── */}
                <section id="about" className="legal-section">
                    <div className="legal-section-label">01 / About</div>
                    <div className="legal-section-body">
                        <h2>About Notes-AI</h2>
                        <p>
                            Notes-AI is a web-based application that helps users capture, organize, and study
                            their notes using artificial intelligence. Users can write and save notes to the cloud,
                            then generate AI-powered study guides from their content with a single click.
                        </p>
                        <p>
                            Notes are organized and clustered automatically, making it easy to review related
                            material across sessions. Notes-AI is designed for students, professionals, and anyone
                            who wants to retain information more effectively.
                        </p>

                        <h3>What We Offer</h3>
                        <ul>
                            <li>Cloud-based note storage and organization</li>
                            <li>AI-generated study guides from your own notes</li>
                            <li>Automatic note clustering and topic grouping</li>
                            <li>Downloadable study materials in plain-text format</li>
                            <li>Monthly subscription plans (Basic, Pro, Premium) billed via Stripe</li>
                        </ul>

                        <h3>Subscription Tiers</h3>
                        <div className="legal-table-wrap">
                            <table className="legal-table">
                                <thead>
                                <tr>
                                    <th>Plan</th>
                                    <th>Price</th>
                                    <th>Billing Period</th>
                                    <th>Features</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Basic</td>
                                    <td>$5 / mo</td>
                                    <td>Monthly</td>
                                    <td>Note storage, cloud sync</td>
                                </tr>
                                <tr>
                                    <td>Pro</td>
                                    <td>$10 / mo</td>
                                    <td>Monthly</td>
                                    <td>Basic + AI study guide generation</td>
                                </tr>
                                <tr>
                                    <td>Premium</td>
                                    <td>$25 / mo</td>
                                    <td>Monthly</td>
                                    <td>Pro + priority processing &amp; extended limits</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <p>
                            Subscriptions are billed monthly and can be cancelled or modified at any time through
                            the customer billing portal powered by Stripe. No long-term contracts are required.
                        </p>
                    </div>
                </section>

                {/* ── PRIVACY ── */}
                <section id="privacy" className="legal-section">
                    <div className="legal-section-label">02 / Privacy Policy</div>
                    <div className="legal-section-body">
                        <h2>Privacy Policy</h2>
                        <p className="legal-effective">Effective Date: January 1, {currentYear}</p>

                        <h3>Information We Collect</h3>
                        <p>
                            When you create an account we collect your <strong>username</strong> and{" "}
                            <strong>email address</strong>. When you use paid features, your payment is processed
                            entirely by <strong>Stripe</strong> — we never store your card number, CVV, or full
                            billing details on our servers. We receive only a Stripe customer ID and subscription
                            status.
                        </p>
                        <p>
                            Notes and text you enter are stored in our cloud infrastructure solely to provide the
                            service to you. We do not sell, rent, or share the content of your notes with third
                            parties for advertising or marketing purposes.
                        </p>

                        <h3>How We Use Your Information</h3>
                        <ul>
                            <li>To authenticate you and manage your account</li>
                            <li>To store and retrieve your notes on your behalf</li>
                            <li>To generate AI study guides from content you explicitly submit</li>
                            <li>To manage your subscription status via Stripe</li>
                            <li>To send transactional emails (password resets, receipts) when requested</li>
                        </ul>

                        <h3>Data Retention</h3>
                        <p>
                            Your data is retained for as long as your account is active. If you delete your
                            account, your notes and personal information will be removed from our systems within
                            30 days.
                        </p>

                        <h3>Third-Party Services</h3>
                        <p>
                            We use the following third-party services to operate Notes-AI:
                        </p>
                        <ul>
                            <li>
                                <strong>Stripe</strong> — payment processing and subscription management.
                                Stripe's privacy policy is available at{" "}
                                <a href="https://stripe.com/privacy" target="_blank" rel="noreferrer">
                                    stripe.com/privacy
                                </a>.
                            </li>
                            <li>
                                <strong>Google Drive API</strong> — cloud storage for user notes.
                            </li>
                        </ul>

                        <h3>Cookies &amp; Sessions</h3>
                        <p>
                            We use HTTP-only cookies to manage authenticated sessions. No third-party tracking
                            or advertising cookies are used.
                        </p>

                        <h3>Your Rights</h3>
                        <p>
                            You may request access to, correction of, or deletion of your personal data at any
                            time by contacting us at the address below. You can also delete your own account
                            directly within the application.
                        </p>

                        <h3>Changes to This Policy</h3>
                        <p>
                            We may update this Privacy Policy from time to time. Continued use of Notes-AI after
                            changes constitutes acceptance of the revised policy.
                        </p>
                    </div>
                </section>

                {/* ── TERMS ── */}
                <section id="terms" className="legal-section">
                    <div className="legal-section-label">03 / Terms of Service</div>
                    <div className="legal-section-body">
                        <h2>Terms of Service</h2>
                        <p className="legal-effective">Effective Date: January 1, {currentYear}</p>

                        <h3>Acceptance of Terms</h3>
                        <p>
                            By creating an account or using Notes-AI, you agree to these Terms of Service. If
                            you do not agree, please do not use the service.
                        </p>

                        <h3>Eligibility</h3>
                        <p>
                            You must be at least 13 years of age to use Notes-AI. By using the service you
                            represent that you meet this requirement.
                        </p>

                        <h3>Account Responsibilities</h3>
                        <p>
                            You are responsible for maintaining the confidentiality of your account credentials.
                            You agree not to share your login information or allow others to access your account.
                            You are responsible for all activity that occurs under your account.
                        </p>

                        <h3>Acceptable Use</h3>
                        <p>You agree not to:</p>
                        <ul>
                            <li>Use Notes-AI for any illegal purpose or in violation of any applicable law</li>
                            <li>Upload content that is harmful, abusive, or infringes on third-party rights</li>
                            <li>Attempt to reverse-engineer, scrape, or disrupt the service</li>
                            <li>Circumvent any access controls or authentication mechanisms</li>
                        </ul>

                        <h3>Subscriptions &amp; Billing</h3>
                        <p>
                            Paid features require an active subscription. Subscriptions are billed monthly in
                            advance through Stripe. You may cancel at any time via the billing portal; access
                            continues until the end of the current billing period. We do not offer refunds for
                            partial months.
                        </p>

                        <h3>Intellectual Property</h3>
                        <p>
                            Notes you create remain your property. By using the AI study guide feature you grant
                            Notes-AI a limited license to process your content for the sole purpose of generating
                            your requested output. We claim no ownership over your notes.
                        </p>

                        <h3>Disclaimers &amp; Limitation of Liability</h3>
                        <p>
                            Notes-AI is provided "as is" without warranties of any kind. AI-generated study
                            guides may contain errors and should not be the sole source for critical decisions.
                            To the maximum extent permitted by law, Notes-AI shall not be liable for any
                            indirect, incidental, or consequential damages arising from your use of the service.
                        </p>

                        <h3>Termination</h3>
                        <p>
                            We reserve the right to suspend or terminate accounts that violate these terms.
                            You may delete your account at any time from the Account Settings page.
                        </p>

                        <h3>Governing Law</h3>
                        <p>
                            These terms are governed by the laws of the United States. Any disputes shall be
                            resolved in the appropriate courts of competent jurisdiction.
                        </p>

                        <h3>Changes to Terms</h3>
                        <p>
                            We may revise these terms at any time. We will notify users of material changes via
                            email. Continued use of the service after changes constitutes acceptance.
                        </p>
                    </div>
                </section>

                {/* ── CONTACT ── */}
                <section id="contact" className="legal-section">
                    <div className="legal-section-label">04 / Contact</div>
                    <div className="legal-section-body">
                        <h2>Contact Us</h2>
                        <p>
                            For questions about these policies, billing inquiries, or account issues, please reach
                            out:
                        </p>
                        <div className="legal-contact-card">
                            <div className="legal-contact-row">
                                <span className="legal-contact-label">Product</span>
                                <span>Notes-AI</span>
                            </div>
                            <div className="legal-contact-row">
                                <span className="legal-contact-label">Email</span>
                                {/* Replace with your actual support email */}
                                <a>notesaicompany@gmail.com</a>
                            </div>
                            <div className="legal-contact-row">
                                <span className="legal-contact-label">Response Time</span>
                                <span>Within 2 business days</span>
                            </div>
                        </div>
                    </div>
                </section>

            </main>

            <footer className="legal-footer">
                <p>&copy; {currentYear} Notes-AI. All rights reserved.</p>
                <div className="legal-footer-links">
                    <a href="#privacy">Privacy Policy</a>
                    <a href="#terms">Terms of Service</a>
                </div>
            </footer>
        </div>
    );
};