import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import retryAuth from "./functions/retryAuth";
import BASE_URL from "../config.js";
/**
 * Generated by claude
 *
 * @param children
 * @returns {*|JSX.Element}
 * @constructor
 */
export const ProtectedRoute = ({ children }) => {
    const [authState, setAuthState] = useState("loading"); // "loading" | "auth" | "unauth"

    useEffect(() => {
        const checkAuth = async () => {
            try {
                const response = await retryAuth(`${BASE_URL}/account/user-details`, {
                    credentials: "include",
                });

                if (response.ok) {
                    setAuthState("auth");
                } else {
                    setAuthState("unauth");
                }
            } catch (err) {
                // retryAuth throws if refresh also fails
                setAuthState("unauth");
            }
        };

        checkAuth();
    }, []);

    if (authState === "loading") {
        return (
            <div style={styles.wrapper}>
                <div style={styles.spinner} />
            </div>
        );
    }

    if (authState === "unauth") {
        return <Navigate to="/" replace />;
    }

    return children;
};

const styles = {
    wrapper: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        width: "100vw",
        backgroundColor: "#faf9f6",
    },
    spinner: {
        width: "36px",
        height: "36px",
        border: "3px solid #e0ddd6",
        borderTop: "3px solid #2d5a27",
        borderRadius: "50%",
        animation: "spin 0.8s linear infinite",
    },
};

// inject the keyframe globally once
const styleTag = document.createElement("style");
styleTag.textContent = `@keyframes spin { to { transform: rotate(360deg); } }`;
document.head.appendChild(styleTag);