spring.application.name=spring-boot-backend-fork

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/mydb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.cleanDisabled=false


stripe.api.key=${STRIPE_TEST_KEY}
stripe.endpoint.secret=${STRIPE_ENDPOINT_SECRET}
front.end.url=http://localhost:3000

rclone.user=${RCLONE_USER}
rclone.password=${RCLONE_PASS}
open.api-key=${OPENAI_API_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_LOGIN_USERNAME}
spring.mail.password=${SMTP_LOGIN_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

salted.key=${SALTED_KEY}
jwt.secret=${JWT_SECRET}
